on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test action
        uses: ./ # Uses an action in the root directory
        with:
          server-url: 'http://143.159.186.16:3000'
          server-auth: ${{ secrets.TEST_OBSERVABLILITY_SERVER_AUTH }}
